name: Deploy to server test

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} to install dependencies & build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "package.json,yarn.lock,.next,ecosystem.config.js"
          target: ${{ secrets.APP_DIR }}/${{ github.event.repository.name }}
          debug: true

      - name: Run command via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.APP_DIR }}/${{ github.event.repository.name }}
            yarn install
            pm2 delete -s ${{ github.event.repository.name }} || :
            pm2 start dist/main.js --name ${{ github.event.repository.name }}
            pm2 save
